// ============================================================
//  THE BRIDGE PUBLIC — data.js
//  Bible API, NT books, translations, quizzes, daily verses
// ============================================================

const API_BASE = 'https://rest.api.bible/v1';
const API_KEY  = 'ozqLpbgad1oi6ci7R8T3a';

const TRANSLATIONS = {
  KJV:  { id: 'de4e12af7f28f599-02', label: 'King James Version',           short: 'KJV'  },
  NIV:  { id: '78a9f6124f344018-01', label: 'New International Version',    short: 'NIV'  },
  NLT:  { id: 'd6e14a625393b4da-01', label: 'New Living Translation',        short: 'NLT'  },
  NASB: { id: 'b8ee27bcd1cae43a-01', label: 'New American Standard (1995)', short: 'NASB' },
};

const BOOK_IDS = {
  matthew:'MAT', mark:'MRK', luke:'LUK', john:'JHN', acts:'ACT',
  romans:'ROM', '1corinthians':'1CO', '2corinthians':'2CO',
  galatians:'GAL', ephesians:'EPH', philippians:'PHP', colossians:'COL',
  '1thessalonians':'1TH', '2thessalonians':'2TH',
  '1timothy':'1TI', '2timothy':'2TI', titus:'TIT', philemon:'PHM',
  hebrews:'HEB', james:'JAS', '1peter':'1PE', '2peter':'2PE',
  '1john':'1JN', '2john':'2JN', '3john':'3JN', jude:'JUD', revelation:'REV',
};

const NT_BOOKS = [
  {id:'matthew',name:'Matthew',abbr:'Matt',chapters:28,author:'Matthew (Levi), tax collector & apostle',audience:'Jewish believers and seekers',purpose:'Prove Jesus is the promised Messiah — fulfillment of Old Testament prophecy',period:'~AD 50–70',culture:'Written in a Jewish context with ~65 fulfilled OT prophecies',fit:'Opens the NT as a bridge from the OT — "Son of David" connects Jesus to all prior promises',wordCounts:[755,1418,677,1225,4401,1171,987,1243,1134,1340,1241,756,1122,1251,1155,1284,1155,734,1225,1200,1100,1350,1256,943,1295,1456,1123,1350]},
  {id:'mark',name:'Mark',abbr:'Mark',chapters:16,author:'John Mark, companion of Peter',audience:'Roman (Gentile) believers',purpose:'Present Jesus as the powerful Servant of God — emphasis on action and miracles',period:'~AD 55–65',culture:'Written for Romans; Greek culture valued power and deeds over words',fit:'The fastest Gospel — no genealogy, straight to action. Jesus as the ultimate Servant.',wordCounts:[945,845,1200,800,1100,1050,1310,1200,1050,900,1100,1250,1450,1350,870,910]},
  {id:'luke',name:'Luke',abbr:'Luke',chapters:24,author:'Luke, a physician and companion of Paul',audience:'Gentile readers, specifically Theophilus',purpose:'Provide an orderly, historically verified account of Jesus\' life and ministry',period:'~AD 60–62',culture:'Greek culture valued careful investigation — Luke writes as a careful historian',fit:'Most detailed Gospel. Emphasizes compassion for outcasts, women, and Gentiles. Pairs with Acts.',wordCounts:[680,940,1180,1340,1300,1540,720,780,1350,1260,1140,1260,1390,1040,1350,1320,1230,1200,1450,1050,1220,1180,980,1240]},
  {id:'john',name:'John',abbr:'John',chapters:21,author:'John, the apostle Jesus loved',audience:'All believers — written to produce and deepen faith',purpose:'Declare Jesus is the divine Son of God so readers may believe and have eternal life',period:'~AD 85–95',culture:'Written later, addressing early theological questions about Jesus\' identity',fit:'The spiritual Gospel. Rich in theology, "I Am" statements, and miraculous signs.',wordCounts:[910,1050,1070,1200,1250,1100,880,1380,1700,1200,1250,1180,1300,1550,1200,1630,1180,1380,880,1120,1360]},
  {id:'acts',name:'Acts',abbr:'Acts',chapters:28,author:'Luke, the physician',audience:'Theophilus and all believers',purpose:'Document the birth and explosive growth of the early church through the Holy Spirit',period:'~AD 62',culture:'Roman Empire at its height — Paul travels roads built for commerce and military',fit:'Sequel to Luke. Bridges Jesus\' departure to the church age we live in now.',wordCounts:[1050,870,1340,1280,1160,1200,1390,1240,1390,1300,1420,1560,1200,1300,1430,1250,1360,1480,1200,1350,1290,1380,1450,1220,1460,1380,1290,1310]},
  {id:'romans',name:'Romans',abbr:'Rom',chapters:16,author:'Paul the Apostle',audience:'Jewish and Gentile believers in Rome',purpose:'The most systematic explanation of the Gospel — sin, salvation, grace, and Christian living',period:'~AD 57',culture:'Rome was the center of world power — Paul reaches the empire\'s heart with the Gospel',fit:'Called the Cathedral of the Christian Faith. Underpins much of NT theological understanding.',wordCounts:[1100,1200,1050,1380,1500,1350,1200,1550,1380,1200,1440,1250,1380,1200,1100,1280]},
  {id:'1corinthians',name:'1 Corinthians',abbr:'1 Cor',chapters:16,author:'Paul the Apostle',audience:'The church in Corinth — wealthy, divided, morally permissive',purpose:'Address division, immorality, spiritual gifts, and the resurrection',period:'~AD 55',culture:'Corinth was a crossroads city — diverse, wealthy, filled with competing philosophies',fit:'Practical church letter addressing timeless issues still present in churches today.',wordCounts:[950,1450,1200,1350,1300,1450,1450,1350,1200,1350,1450,1550,1350,1450,1200,1100]},
  {id:'2corinthians',name:'2 Corinthians',abbr:'2 Cor',chapters:13,author:'Paul the Apostle',audience:'The church in Corinth',purpose:'Defend Paul\'s apostleship and encourage generosity and reconciliation',period:'~AD 56',culture:'The most emotionally personal of Paul\'s letters — written after a painful visit',fit:'Shows Paul\'s heart. Key passage on God\'s strength in weakness (2 Cor 12:9).',wordCounts:[1350,1200,1100,1250,1380,1200,1300,1150,1350,1200,1400,1250,1380]},
  {id:'galatians',name:'Galatians',abbr:'Gal',chapters:6,author:'Paul the Apostle',audience:'Churches in Galatia facing pressure to add Jewish law to the Gospel',purpose:'Defend salvation by grace through faith alone — the Magna Carta of Christian liberty',period:'~AD 49',culture:'Judaizers were teaching Gentile believers they must follow Mosaic law to be truly saved',fit:'Closely linked to Romans. Luther\'s rediscovery of Galatians sparked the Reformation.',wordCounts:[1350,1500,1450,1550,1400,1300]},
  {id:'ephesians',name:'Ephesians',abbr:'Eph',chapters:6,author:'Paul the Apostle (from prison)',audience:'The church at Ephesus and surrounding churches',purpose:'Reveal God\'s eternal plan to unite all things in Christ; call believers to walk worthy',period:'~AD 60–62',culture:'Ephesus was home to the temple of Artemis — a major center of pagan religion',fit:'Ch 1–3: what God did for us in Christ. Ch 4–6: how we should live in response.',wordCounts:[1350,1500,1350,1450,1400,1350]},
  {id:'philippians',name:'Philippians',abbr:'Phil',chapters:4,author:'Paul the Apostle (from prison)',audience:'The church at Philippi — Paul\'s most beloved church',purpose:'Express joy and thankfulness; exhort believers to unity and contentment in all things',period:'~AD 61',culture:'Philippi was a Roman colony with strong civic pride — Paul uses citizenship language',fit:'The Joy Letter — rejoice appears 16 times despite Paul writing from prison.',wordCounts:[1350,1500,1400,1350]},
  {id:'colossians',name:'Colossians',abbr:'Col',chapters:4,author:'Paul the Apostle (from prison)',audience:'The church at Colossae facing false teaching about angels and rituals',purpose:'Assert the absolute supremacy and sufficiency of Jesus Christ over all things',period:'~AD 60–62',culture:'Colossae was near Laodicea; the church was likely founded by Epaphras',fit:'Parallel to Ephesians. Christ shown as fully God and head of all creation.',wordCounts:[1350,1450,1400,1300]},
  {id:'1thessalonians',name:'1 Thessalonians',abbr:'1 Thess',chapters:5,author:'Paul the Apostle',audience:'The young church at Thessalonica',purpose:'Encourage a persecuted church and clarify questions about Christ\'s return',period:'~AD 51 (one of Paul\'s earliest letters)',culture:'Thessalonica was a prosperous port city; new believers faced immediate persecution',fit:'Contains the classic passage on the resurrection at Christ\'s return (1 Thess 4:13–18).',wordCounts:[1200,1350,1200,1350,1400]},
  {id:'2thessalonians',name:'2 Thessalonians',abbr:'2 Thess',chapters:3,author:'Paul the Apostle',audience:'The church at Thessalonica, still confused about end times',purpose:'Correct misunderstandings about the Day of the Lord; encourage faithfulness',period:'~AD 51–52',culture:'Some had stopped working, completely convinced Christ was returning immediately',fit:'Completes the end-times teaching begun in 1 Thessalonians.',wordCounts:[1200,1350,1200]},
  {id:'1timothy',name:'1 Timothy',abbr:'1 Tim',chapters:6,author:'Paul the Apostle',audience:'Timothy, Paul\'s young protégé leading the church at Ephesus',purpose:'Instruct Timothy on church order, false teaching, leadership qualifications, and godliness',period:'~AD 62–64',culture:'Ephesus was a challenging city with false teachers and strong pagan influences',fit:'A pastoral epistle — deeply practical guidance for church leaders still relevant today.',wordCounts:[1350,1450,1350,1450,1350,1350]},
  {id:'2timothy',name:'2 Timothy',abbr:'2 Tim',chapters:4,author:'Paul the Apostle (his final letter, before execution)',audience:'Timothy',purpose:'Paul\'s last words — urge Timothy to stay faithful to the Gospel no matter the cost',period:'~AD 67',culture:'Paul is in his final imprisonment in Rome, expecting death under Emperor Nero',fit:'The most personal of Paul\'s letters. Contains 2 Tim 3:16–17 on the nature of Scripture.',wordCounts:[1350,1450,1350,1350]},
  {id:'titus',name:'Titus',abbr:'Titus',chapters:3,author:'Paul the Apostle',audience:'Titus, leading churches in Crete',purpose:'Instruct on appointing elders, teaching sound doctrine, and godly living',period:'~AD 62–64',culture:'Crete had a reputation for dishonesty — Paul quotes a Cretan poet about this',fit:'Companion to 1 Timothy. Sound doctrine always produces godly behavior.',wordCounts:[1350,1400,1200]},
  {id:'philemon',name:'Philemon',abbr:'Phlm',chapters:1,author:'Paul the Apostle',audience:'Philemon, a wealthy slave owner and church leader',purpose:'Appeal to Philemon to receive back his runaway slave Onesimus as a brother in Christ',period:'~AD 61',culture:'Slavery was universal in the Roman Empire — Paul\'s appeal subtly undermines its logic',fit:'The shortest NT letter. A masterpiece of grace, reconciliation, and Christian social ethics.',wordCounts:[450]},
  {id:'hebrews',name:'Hebrews',abbr:'Heb',chapters:13,author:'Unknown (possibly Paul, Apollos, or Barnabas)',audience:'Jewish believers tempted to abandon Christianity and return to Judaism',purpose:'Show Jesus is better than everything in the Old Covenant — angels, Moses, the priesthood',period:'~AD 64–69',culture:'With the temple\'s looming destruction, Jewish believers faced enormous pressure to return',fit:'The great OT-to-NT bridge. Christ fulfills every shadow, type, and covenant promise.',wordCounts:[1450,1350,1550,1650,1400,1500,1350,1500,1450,1350,1450,1300,1400]},
  {id:'james',name:'James',abbr:'Jas',chapters:5,author:'James, the brother of Jesus',audience:'Jewish Christians scattered throughout the world',purpose:'Practical wisdom — real faith must produce real action, or it is not genuine faith',period:'~AD 45–50 (possibly the earliest NT letter)',culture:'Written to scattered Jewish believers facing persecution and trials',fit:'The Proverbs of the NT. James and Paul perfectly complement each other on faith and works.',wordCounts:[1350,1500,1450,1450,1350]},
  {id:'1peter',name:'1 Peter',abbr:'1 Pet',chapters:5,author:'Peter the Apostle',audience:'Christians scattered across Asia Minor facing persecution',purpose:'Encourage believers to stand firm in suffering and live holy lives before a watching world',period:'~AD 62–64',culture:'Nero\'s persecution was beginning — believers were becoming social outcasts',fit:'A letter of hope in hardship. Connects our suffering with Christ\'s suffering and future glory.',wordCounts:[1350,1450,1400,1350,1250]},
  {id:'2peter',name:'2 Peter',abbr:'2 Pet',chapters:3,author:'Peter the Apostle (his final letter)',audience:'All believers',purpose:'Warn against false teachers and urge growth in the true knowledge of Christ',period:'~AD 67–68',culture:'Peter writes knowing his death is imminent, much like Paul in 2 Timothy',fit:'Companion to Jude. Both warn about false teaching that increases as the end approaches.',wordCounts:[1350,1550,1350]},
  {id:'1john',name:'1 John',abbr:'1 Jn',chapters:5,author:'John the Apostle',audience:'Believers facing early Gnostic teaching denying that Christ came in the flesh',purpose:'Confirm genuine faith through love, obedience, and the true confession of Christ',period:'~AD 85–95',culture:'Gnosticism taught spirit is good and matter is evil — Jesus couldn\'t really be fully human',fit:'Warm, pastoral, and full of assurance. "God is love" appears here (1 John 4:8, 16).',wordCounts:[1350,1500,1450,1550,1350]},
  {id:'2john',name:'2 John',abbr:'2 Jn',chapters:1,author:'John the Apostle',audience:'A specific congregation ("the elect lady") or an individual believer',purpose:'Urge believers to walk in love and truth, and not to welcome false teachers into fellowship',period:'~AD 85–95',culture:'False teachers were traveling between house churches — John warns not to endorse them',fit:'Only 13 verses. A close companion to 1 John on truth and love.',wordCounts:[300]},
  {id:'3john',name:'3 John',abbr:'3 Jn',chapters:1,author:'John the Apostle',audience:'Gaius, a faithful and hospitable believer',purpose:'Commend Gaius for his hospitality and warn about Diotrephes who loved preeminence',period:'~AD 85–95',culture:'Traveling missionaries depended entirely on local believers for lodging and support',fit:'A personal note revealing church dynamics and leadership tensions in the early church.',wordCounts:[300]},
  {id:'jude',name:'Jude',abbr:'Jude',chapters:1,author:'Jude, brother of James and Jesus',audience:'All believers',purpose:'Urgently warn about false teachers who had secretly infiltrated the church',period:'~AD 65–80',culture:'False teachers were twisting grace into a license for immorality and sin',fit:'Closely parallel to 2 Peter. A bold call to contend earnestly for the faith (Jude 3).',wordCounts:[600]},
  {id:'revelation',name:'Revelation',abbr:'Rev',chapters:22,author:'John the Apostle (in exile on the island of Patmos)',audience:'Seven churches in Asia Minor and all believers throughout history',purpose:'Reveal the ultimate victory of Christ over evil; call the church to faithful endurance',period:'~AD 95',culture:'Emperor Domitian demanded worship as a god — Christians faced death for refusing',fit:'The grand finale of the entire Bible. Every OT theme, symbol, and promise is completed.',wordCounts:[1350,1450,1350,1200,1400,1350,1450,1300,1450,1350,1200,1350,1450,1500,1350,1450,1350,1500,1350,1450,1400,1500]},
];

const NT_TOTAL_CHAPTERS = NT_BOOKS.reduce((s, b) => s + b.chapters, 0); // 260

const DAILY_VERSES = [
  {text:"For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", ref:"John 3:16 (KJV)"},
  {text:"I can do all things through Christ which strengtheneth me.", ref:"Philippians 4:13 (KJV)"},
  {text:"And we know that all things work together for good to them that love God, to them who are the called according to his purpose.", ref:"Romans 8:28 (KJV)"},
  {text:"There is therefore now no condemnation to them which are in Christ Jesus.", ref:"Romans 8:1 (KJV)"},
  {text:"For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", ref:"Ephesians 2:8 (KJV)"},
  {text:"Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", ref:"Philippians 4:6 (KJV)"},
  {text:"For the word of God is quick, and powerful, and sharper than any twoedged sword.", ref:"Hebrews 4:12 (KJV)"},
  {text:"Trust in the LORD with all thine heart; and lean not unto thine own understanding.", ref:"Proverbs 3:5 (KJV)"},
  {text:"I am the way, the truth, and the life: no man cometh unto the Father, but by me.", ref:"John 14:6 (KJV)"},
  {text:"All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.", ref:"2 Timothy 3:16 (KJV)"},
  {text:"Come unto me, all ye that labour and are heavy laden, and I will give you rest.", ref:"Matthew 11:28 (KJV)"},
  {text:"God is love.", ref:"1 John 4:8 (KJV)"},
  {text:"But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", ref:"Matthew 6:33 (KJV)"},
  {text:"Now faith is the substance of things hoped for, the evidence of things not seen.", ref:"Hebrews 11:1 (KJV)"},
  {text:"In the beginning was the Word, and the Word was with God, and the Word was God.", ref:"John 1:1 (KJV)"},
  {text:"The LORD is my shepherd; I shall not want.", ref:"Psalm 23:1 (KJV)"},
  {text:"Rejoice in the Lord alway: and again I say, Rejoice.", ref:"Philippians 4:4 (KJV)"},
  {text:"And the Word was made flesh, and dwelt among us, full of grace and truth.", ref:"John 1:14 (KJV)"},
  {text:"Be not overcome of evil, but overcome evil with good.", ref:"Romans 12:21 (KJV)"},
  {text:"I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth.", ref:"Romans 1:16 (KJV)"},
  {text:"Thy word is a lamp unto my feet, and a light unto my path.", ref:"Psalm 119:105 (KJV)"},
];

// ── QUIZZES — exactly 3 per chapter ──────────────────────
const QUIZZES = {
  'matthew-1':[
    {q:"Matthew 1:1 calls Jesus 'the son of David, the son of Abraham.' What is the significance of these two names?",options:["They prove Jesus had royal blood","They connect Jesus to God's covenant promises to both men","They show Jesus was the greatest teacher","They prove the Jewish people accepted Jesus"],correct:1,explain:"Matthew opens by connecting Jesus to two critical covenant promises: God's promise to Abraham that all nations would be blessed through his seed (Gen 12:3), and God's promise to David of an eternal kingdom through his descendant (2 Sam 7:12–13). Jesus is the fulfillment of both.",ref:"Matthew 1:1; Genesis 12:3; 2 Samuel 7:12–13"},
    {q:"How did Mary become pregnant according to Matthew 1:18?",options:["Joseph was the biological father","Through the Holy Ghost, before she and Joseph came together","An angel physically visited her","Matthew does not explain this"],correct:1,explain:"Matthew 1:18 clearly states she 'was found with child of the Holy Ghost' before she and Joseph came together. This directly fulfilled the prophecy of Isaiah 7:14 — 'a virgin shall conceive and bear a son.'",ref:"Matthew 1:18; Isaiah 7:14"},
    {q:"What does the name JESUS mean according to the angel's instruction in Matthew 1:21?",options:["God with us","He shall save his people from their sins","King of the Jews","Son of the Most High"],correct:1,explain:"The angel declares: 'thou shalt call his name JESUS: for he shall save his people from their sins.' The name Yeshua (Jesus in Hebrew) literally means 'The LORD saves.' His very name announces His mission.",ref:"Matthew 1:21; Acts 4:12; Luke 2:11"}
  ],
  'john-1':[
    {q:"John 1:1 says 'the Word was God.' What three things does John 1:1–3 tell us about the Word?",options:["He was created, then sent, then became flesh","He was with God from the beginning, He was God, and all things were made through Him","He was a prophet, a teacher, and a healer","He was written, spoken, and fulfilled in order"],correct:1,explain:"John 1:1–3 states: (1) the Word existed in the beginning, (2) the Word was with God as a distinct person, (3) the Word was fully God, and (4) all creation came through Him. John deliberately echoes Genesis 1:1 to show Jesus was present at and active in creation.",ref:"John 1:1–3; Genesis 1:1; Colossians 1:16–17"},
    {q:"John 1:12 says those who receive Jesus are given the right to become what?",options:["Disciples of John the Baptist","Workers of miracles","The sons of God","Teachers of the law"],correct:2,explain:"John 1:12 — 'to them gave he power to become the sons of God, even to them that believe on his name.' This is adoption into God's own family — not earned by birth or religious achievement, but received through personal faith in Jesus.",ref:"John 1:12–13; Romans 8:15–17; Galatians 3:26"},
    {q:"John 1:14 says 'the Word was made flesh.' What two qualities does John say characterized Jesus?",options:["Power and holiness","Grace and truth","Wisdom and strength","Love and justice"],correct:1,explain:"John 1:14 — 'full of grace and truth.' Grace (undeserved favor freely given) and truth (absolute faithfulness and reality) are the two defining marks of the incarnate Christ — showing both His infinite mercy and His uncompromising integrity.",ref:"John 1:14, 17; Exodus 34:6; Psalm 85:10"}
  ],
  'romans-8':[
    {q:"Romans 8:1 declares 'no condemnation' to whom?",options:["To all people everywhere because God is merciful","To those who keep the Ten Commandments","To them which are in Christ Jesus","To the Jewish nation under the covenant"],correct:2,explain:"Romans 8:1 — 'no condemnation to them which are in Christ Jesus.' The critical phrase is 'in Christ Jesus.' Our standing before God is based entirely on Christ's righteousness credited to us through faith — not on our own performance or track record.",ref:"Romans 8:1; 2 Corinthians 5:21; Romans 5:1"},
    {q:"Romans 8:28 promises all things work together for good. What two conditions does Paul give?",options:["Those who pray every day and fast regularly","Those who love God and are called according to His purpose","Those who have never committed a serious sin","Those who tithe faithfully and serve in church"],correct:1,explain:"Romans 8:28 has two specific conditions: loving God AND being called according to His purpose. This is a covenant promise for those in relationship with God — not a blanket guarantee that everything works out for everyone regardless.",ref:"Romans 8:28; Jeremiah 29:11; Ephesians 1:11"},
    {q:"Romans 8:38–39 lists things that CANNOT separate us from God's love. Which of these appears on Paul's list?",options:["Willful and persistent sin","Abandoning the church and fellowship","Neither death nor life, neither angels nor principalities","Persistent doubt about God's existence"],correct:2,explain:"Romans 8:38–39 lists external cosmic forces: death, life, angels, principalities, powers, things present, things to come, height, depth, and any other creature. Paul is declaring the total security of God's covenant love for those in Christ — nothing in all creation can sever it.",ref:"Romans 8:38–39; John 10:28–29; Psalm 139:7–10"}
  ],
  'ephesians-2':[
    {q:"Ephesians 2:1 describes our condition before salvation as what?",options:["Spiritually sick and needing help","Dead in trespasses and sins","Lost but still actively seeking God","Imperfect but fundamentally good"],correct:1,explain:"Ephesians 2:1 — 'dead in trespasses and sins.' Not spiritually sick — completely dead. We had no spiritual life and absolutely could not save ourselves. This is what makes grace so staggering: God made alive those who were completely dead.",ref:"Ephesians 2:1; Colossians 2:13; Romans 5:6"},
    {q:"Ephesians 2:8–9 says salvation is by grace through faith. What does Paul explicitly say it is NOT?",options:["Not of emotions or spiritual experiences","Not of yourselves — it is the gift of God, not of works","Not of prayer or religious worship","Not of church attendance or Bible reading"],correct:1,explain:"Ephesians 2:8–9 — 'not of yourselves: it is the gift of God: not of works, lest any man should boast.' Three separate negatives remove every human contribution to salvation. It is entirely God's initiative, God's gift, and God's power.",ref:"Ephesians 2:8–9; Romans 3:27–28; Titus 3:5"},
    {q:"Ephesians 2:10 calls us God's 'workmanship' created for what purpose?",options:["To praise and worship Him in church forever","Good works which God prepared beforehand that we should walk in them","To spread the gospel to every nation on earth","To keep the commandments of the Law of Moses"],correct:1,explain:"Ephesians 2:10 — 'created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.' Works flow from salvation as its natural fruit and evidence — they never produce salvation. We are saved for good works, not by good works.",ref:"Ephesians 2:10; James 2:17–18; Titus 2:14"}
  ],
  'philippians-4':[
    {q:"Philippians 4:6 says 'be careful for nothing.' What does Paul instruct us to do instead?",options:["Work harder and trust our own ability to solve problems","In every thing by prayer and supplication with thanksgiving present our requests to God","Fast and pray intensely until the problem is resolved","Wait silently without bringing it to God"],correct:1,explain:"Philippians 4:6 — instead of anxiety, bring absolutely everything to God through prayer, supplication, and thanksgiving. The immediate result in verse 7 is 'the peace of God, which passeth all understanding' acting as a guard over our hearts and minds in Christ.",ref:"Philippians 4:6–7; 1 Peter 5:7; Matthew 6:25–34"},
    {q:"What is the context Paul is speaking from when he writes 'I can do all things through Christ' (Philippians 4:13)?",options:["He is about to plant a major new church","He is describing miraculous healing and supernatural powers","He has learned contentment in all circumstances — in need and in plenty alike","He is encouraging Timothy to preach boldly despite opposition"],correct:2,explain:"Philippians 4:11–13 — Paul says he has 'learned' contentment in every state: hungry or full, abased or abounding. The 'all things' he can do refers to enduring every circumstance through Christ's strength — not unlimited miraculous ability.",ref:"Philippians 4:11–13; 2 Corinthians 12:9–10; Hebrews 13:5"},
    {q:"Why does Paul emphasize the thought life in Philippians 4:8, instructing believers to think on things that are true, honest, just, pure, and lovely?",options:["Because God directly judges every thought we have","Because what we consistently dwell on shapes what we do and who we become","Because negative thoughts immediately and permanently grieve the Holy Spirit","Because positive thinking produces physical health and material blessing"],correct:1,explain:"Philippians 4:8 flows directly into verse 9 — 'those things do.' What we meditate on forms our character and determines our actions. Proverbs 23:7 confirms: 'as he thinketh in his heart, so is he.' Romans 12:2 calls this the renewing of the mind.",ref:"Philippians 4:8–9; Proverbs 23:7; Romans 12:2"}
  ],
  'hebrews-11':[
    {q:"Hebrews 11:1 defines faith as 'the substance of things hoped for.' What is the second part of that definition?",options:["The fulfillment of things already seen and proven","The evidence of things not seen","The record of things written in Scripture","The answer to things prayed for earnestly"],correct:1,explain:"Hebrews 11:1 — 'the evidence of things not seen.' Biblical faith is not blind — it has genuine substance and evidence — but it operates in the realm of the unseen. It takes God at His word before circumstances confirm what He has promised.",ref:"Hebrews 11:1; 2 Corinthians 5:7; Romans 10:17"},
    {q:"Hebrews 11:6 states that without faith it is impossible to do what?",options:["Receive the gift of the Holy Spirit","Please God","Understand and interpret the Scriptures","Enter into the fellowship of the church"],correct:1,explain:"Hebrews 11:6 — 'without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.' Both belief in God's existence and trust in His character and promises are required.",ref:"Hebrews 11:6; Romans 14:23; James 1:6–8"},
    {q:"Hebrews 12:1–2 instructs believers to run the race 'looking unto' whom?",options:["The great cloud of witnesses — Abel, Noah, Abraham, and Moses","Our fellow believers and brothers and sisters for encouragement","Jesus, the author and finisher of our faith","The prophets and apostles who suffered before us"],correct:2,explain:"Hebrews 12:2 — 'looking unto Jesus the author and finisher of our faith.' After the entire gallery of faith heroes in chapter 11, the author makes the decisive turn: fix your eyes on Jesus alone as the ultimate example and the One who brings our faith to its completion.",ref:"Hebrews 12:1–2; Philippians 3:14; 1 Corinthians 9:24–25"}
  ],
  'james-1':[
    {q:"James 1:2 says to 'count it all joy' when you fall into trials. Why does James say this?",options:["Because trials are a sign that God is punishing unconfessed sin","Because the trying of your faith worketh patience, which leads to spiritual maturity","Because suffering earns God's favor and future blessing","Because other believers are watching to see if your faith is real"],correct:1,explain:"James 1:3–4 — 'the trying of your faith worketh patience; but let patience have her perfect work, that ye may be perfect and entire, wanting nothing.' Trials are not punishment — they are God's chosen process for building complete, mature character that nothing else can produce.",ref:"James 1:2–4; Romans 5:3–5; 1 Peter 1:6–7"},
    {q:"James 1:5 says if anyone lacks wisdom they should do what?",options:["Seek counsel from the elders of the church","Study more Scripture on their own until wisdom comes","Ask of God, who gives to all men liberally and does not rebuke","Fast and pray intensely for forty days"],correct:2,explain:"James 1:5 — 'let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.' God does not scold us for not knowing — He generously gives wisdom to anyone who asks in faith. This is a direct, unconditional promise.",ref:"James 1:5; Proverbs 2:6; Matthew 7:7–8"},
    {q:"James 1:22 warns believers against being a certain kind of person. Which person is he warning against?",options:["A doubter who prays without genuine faith","A hearer of the word only, and not a doer — deceiving yourself","A person who never reads or studies Scripture","Someone who attends church but refuses to give financially"],correct:1,explain:"James 1:22 — 'be ye doers of the word, and not hearers only, deceiving your own selves.' He follows with the mirror illustration (vv.23–24): a person who hears but doesn't act is like someone who looks carefully in a mirror, walks away, and immediately forgets what they look like.",ref:"James 1:22–25; Matthew 7:24–27; Luke 11:28"}
  ],
  'revelation-1':[
    {q:"Revelation 1:3 gives a specific blessing to those who do what three things?",options:["Understand all the symbolism and prophecies of Revelation","Read, hear, and keep the words of this prophecy","Preach the book of Revelation to unbelievers","Study Revelation only with a qualified teacher"],correct:1,explain:"Revelation 1:3 — 'Blessed is he that readeth, and they that hear the words of this prophecy, and keep those things which are written therein.' This is the only book of the Bible that specifically promises a blessing to those who read, hear, and obey it.",ref:"Revelation 1:3; Revelation 22:7; James 1:22"},
    {q:"In Revelation 1:8, God describes Himself with a phrase that appears three times in the book. What is it?",options:["The Holy One of Israel, unchanging forever","The Ancient of Days, enthroned on high","The Alpha and Omega, who is, was, and is to come, the Almighty","The King of Kings and Lord of Lords over all creation"],correct:2,explain:"Revelation 1:8 — 'I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the Almighty.' Alpha and Omega are the first and last letters of the Greek alphabet — God encompasses all of existence, time, and reality.",ref:"Revelation 1:8; Isaiah 44:6; Revelation 22:13"},
    {q:"Why was John on the island of Patmos when he received the Revelation?",options:["He voluntarily went there for extended prayer and fasting","He was shipwrecked on his way to preach in Rome","He was exiled there as a prisoner for the word of God and the testimony of Jesus Christ","He was sent there by the Jerusalem church to establish a new congregation"],correct:2,explain:"Revelation 1:9 — John says he was on Patmos 'for the word of God, and for the testimony of Jesus Christ.' He was exiled there as a prisoner under Roman persecution — almost certainly under Emperor Domitian around AD 95, who demanded divine worship.",ref:"Revelation 1:9; Acts 14:22; 2 Timothy 3:12"}
  ],
};
